api:
    resource: '@AppBundle/Controller/'
    type: annotation
    prefix:   /api/
    defaults:
        _format: json

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc
